/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package urnaeletronica;
import javax.swing.*;

public class App {
    

    public static void main(String[] args) {
        // Landing Page screen
        JFrame frame = new JFrame("Urna Eletronica");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(1200, 646);
        //change background color to #FFFFFF
        frame.getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
        frame.setVisible(true);

    }
}
